 create table if not exists users (
     id bigint generated by default as identity primary key ,
     first_name varchar(30) not null ,
     last_name varchar(30) not null ,
     email varchar(50) not null unique ,
     password varchar not null,
     role varchar(20) not null
 );

 create table if not exists refresh_token (
     id int generated by default as identity primary key,
     user_id int references users (id) on delete cascade ,
     token varchar not null,
     expiry_date timestamp not null
 );

 create table if not exists products(
                                        id bigint generated by default as identity primary key ,
                                        user_id bigint references users(id),
                                        title varchar(100) not null ,
                                        description varchar(5000) ,
                                        price bigint not null ,
                                        category varchar not null
 )